# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: sqlserver
name: dbatools
version: 2.2.1
readme: README.md
authors:
  - Frank Henninger (github.com/OsirisDBA)
description: An ansible collection that wraps the dbatools powershell module. Based upon lowlydba.sqlserver by John McCall (github.com/lowlydba)
license_file: LICENSE
tags:
  # tags so people can search for collections https://galaxy.ansible.com/search
  # tags are all lower-case, no spaces, no dashes.
  - sqlserver
  - mssql
  - database
repository: https://github.com/OsirisDBA/sqlserver.dbatools
documentation: https://github.com/OsirisDBA/sqlserver.dbatools
homepage: https://github.com/OsirisDBA/sqlserver.dbatools
issues: https://github.com/OsirisDBA/sqlserver.dbatools/issues
build_ignore:
  # https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - .gitattributes
  - changelogs/.plugin-cache.yaml
  - .vscode/
  - .github/
  - MAINTAINING.md
  - REVIEW_CHECKLIST.md
